### ISSUE TITLE
Add the URL in the repository details section

### ISSUE THREAD

**Issue by baumannzone** [heedrox/abbreviame#7]
Hello, Jordi. In case you didn't know, you can add the URL of your website in the repository details section. It would look like the image below, much more pro 🔥.

Just click on the ⚙️ icon and add it.

![image](https://user-images.githubusercontent.com/5422102/225631736-947ff2b0-a441-4249-97b6-a68657ee2682.png)

**Comment by heedrox** [comment]
Done! Thanks for letting me know!

<img width="336" alt="image" src="https://user-images.githubusercontent.com/991738/226112755-5aa53045-4269-487d-befc-17e246553cd4.png">
